flags:
  text:
    integer-simple: false
extra-package-dbs: []
packages:
- .
extra-deps:
- aeson-0.11.1.4
- base-compat-0.9.3
- base-orphans-0.6
- bytestring-builder-0.10.8.1.0
- fast-logger-2.4.10
- hex-0.1.2
- ideas-1.6
- kan-extensions-5.0.2
- lens-4.14
- mmorph-1.1.0
- parsec-3.1.9
- servant-server-0.7
- text-1.2.1.3
- unix-compat-0.5.0.1
- unix-time-0.3.7
- unordered-containers-0.2.5.1
- wai-extra-3.0.21.0
resolver: lts-6.1
